version: "3.3"

services:
  traefik:
    container_name: traefik
    image: "traefik:v2.2"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      - --api.dashboard=true
      - --log.level=DEBUG
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      - --certificatesresolvers.leresolver.acme.email=$email
      - --certificatesresolvers.leresolver.acme.storage=.acme/acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ".acme/acme.json:/acme.json"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`$url_dashboard`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=$httpd-auth"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - viernes

  nextcloud:
    container_name: nextcloud
    image: "nextcloud:latest"
    environment:
#      - NEXTCLOUD_ADMIN_USER=nacho
#      - NEXTCLOUD_ADMIN_PASSWORD=123456
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=$trusted_domain
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`$url_nextcloud`)"
      - "traefik.http.routers.nextcloud.tls.certresolver=leresolver"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
    volumes:
      - ./nextcloud/html:/var/www/html
      - ./nextcloud/apps:/var/www/html/custom_apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    depends_on:
      - "postgres"
    networks:
      - viernes

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=nextcloud
    volumes:
      - ./base:/var/lib/postgresql/data
    networks:
      - viernes

networks:
  viernes:
    external: true
